-- V3 Phase 6 — cycle close: carry forward, extras, complimentary.
--
-- Structure (the billable_items table plus the BillableKind and
-- BillableStatus enums) is applied by `prisma db push`. This mirrors it.
-- Idempotent — safe to re-run.
--
-- There is no backfill: billable items are produced by CLOSING a cycle, and
-- no cycle has been closed before this phase existed. Cycles already marked
-- closed by hand (there should be none) would need their lines generated by
-- reopening and re-closing them through the wizard.

BEGIN;

-- Belt and braces: v2 marked over-delivery with isExtra only. Anything still
-- carrying that flag without a billing intent is a billable extra, so cycle
-- close offers it in step 3 rather than folding it silently into the package.
UPDATE content_items
   SET "billingIntent" = 'EXTRA_BILLABLE'
 WHERE "isExtra" = TRUE
   AND "billingIntent" = 'INCLUDED';

COMMIT;
