-- PART 1 of 2: STRUCTURE
-- Generated by scripts/prepare-production-migration.ts
--
-- Tables, columns, enums and indexes the target database is missing,
-- derived by diffing it against prisma/schema.prisma.
--
-- !! 9 DESTRUCTIVE STATEMENT(S) below drop a table or column:
--      ALTER TABLE "contract_parties" DROP COLUMN "stakeholderId";
--      ALTER TABLE "expenses" DROP COLUMN "stakeholderId",
--      ALTER TABLE "invoices" DROP COLUMN "quotationId",
--      ALTER TABLE "projects" DROP COLUMN "quotationId",
--      DROP TABLE "company_settings";
--      DROP TABLE "quotation_line_items";
--      DROP TABLE "quotations";
--      DROP TABLE "rate_cards";
--      DROP TABLE "stakeholders";
-- !! If this database holds real data in any of them, that data is gone.
-- !! Take a backup first, and confirm every drop is intended.
--
-- Run this FIRST and let it commit, then run PART 2. They cannot share a
-- transaction: Postgres will not accept a new enum value being used in the
-- same transaction that created it.
--
-- THIS FILE RUNS ONCE. It is a diff, not a migration — re-running it fails
-- on `type "…" already exists`. If it half-applies, regenerate against the
-- database as it now stands rather than re-running this copy. (PART 2 is
-- idempotent and can be re-run freely.)
--
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f docs/PRODUCTION_MIGRATION_1_STRUCTURE.sql
--
SET client_encoding = 'UTF8';

-- CreateEnum
CREATE TYPE "ClientImportance" AS ENUM ('NORMAL', 'IMPORTANT', 'VIP');

-- CreateEnum
CREATE TYPE "Designation" AS ENUM ('SMM', 'DESIGNER', 'EDITOR', 'HEAD_OF_DESIGN', 'PHOTOGRAPHER', 'SME', 'POC', 'OTHER');

-- CreateEnum
CREATE TYPE "TaskKind" AS ENUM ('PLANNING', 'CONTENT_WORK', 'POST', 'GENERAL', 'PERSONAL');

-- CreateEnum
CREATE TYPE "AssignmentStatus" AS ENUM ('NONE', 'PENDING_HEAD_APPROVAL', 'APPROVED', 'REASSIGNED');

-- CreateEnum
CREATE TYPE "DeliveryMethod" AS ENUM ('FILE_UPLOAD', 'LINK', 'WHATSAPP', 'SLACK', 'OTHER');

-- CreateEnum
CREATE TYPE "ChangeRequestStatus" AS ENUM ('OPEN', 'RESOLVED');

-- CreateEnum
CREATE TYPE "ReviewDecision" AS ENUM ('APPROVED', 'CHANGES_REQUESTED');

-- CreateEnum
CREATE TYPE "ContentStatus" AS ENUM ('PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'IN_REVIEW', 'TEAM_APPROVED', 'CLIENT_APPROVED', 'SCHEDULED', 'POSTED', 'MISSED', 'SUBMITTED', 'APPROVED', 'CHANGES_REQUESTED', 'CARRIED_FORWARD');

-- CreateEnum
CREATE TYPE "BillingIntent" AS ENUM ('INCLUDED', 'EXTRA_BILLABLE', 'COMPLIMENTARY');

-- CreateEnum
CREATE TYPE "CarryMode" AS ENUM ('INSIDE_QUOTA', 'ABOVE_QUOTA');

-- CreateEnum
CREATE TYPE "CycleUnit" AS ENUM ('WEEK', 'MONTH', 'QUARTER');

-- CreateEnum
CREATE TYPE "CycleStatus" AS ENUM ('OPEN', 'CLOSED');

-- CreateEnum
CREATE TYPE "BillableKind" AS ENUM ('PACKAGE', 'EXTRA', 'COMPLIMENTARY', 'ADHOC_TASK');

-- CreateEnum
CREATE TYPE "BillableStatus" AS ENUM ('PENDING_PRICING', 'READY', 'INVOICED', 'WAIVED');

-- CreateEnum
CREATE TYPE "TrialRequestStatus" AS ENUM ('NEW', 'CONTACTED', 'CONVERTED', 'DECLINED');

-- CreateEnum
CREATE TYPE "LineItemKind" AS ENUM ('PACKAGE', 'EXTRA', 'COMPLIMENTARY', 'ADHOC_TASK', 'CUSTOM');

-- CreateEnum
CREATE TYPE "ReceiptMethod" AS ENUM ('BANK_TRANSFER', 'CASH', 'CHECK', 'CARD', 'UPI', 'OTHER');

-- CreateEnum
CREATE TYPE "PlanTier" AS ENUM ('TRIAL', 'FULL');

-- CreateEnum
CREATE TYPE "FollowUpStatus" AS ENUM ('PENDING', 'DONE', 'SNOOZED');

-- CreateEnum
CREATE TYPE "EventKind" AS ENUM ('FESTIVAL', 'CAMPAIGN', 'SHOOT', 'INTERNAL', 'OTHER');

-- AlterEnum
ALTER TYPE "ExpenseCategory" ADD VALUE 'COMMISSIONS';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ProjectRole" ADD VALUE 'SMM';
ALTER TYPE "ProjectRole" ADD VALUE 'CONTRIBUTOR';

-- AlterEnum
ALTER TYPE "TaskStatus" ADD VALUE 'CHANGES_REQUESTED';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "UserRole" ADD VALUE 'OWNER';
ALTER TYPE "UserRole" ADD VALUE 'SMM';
ALTER TYPE "UserRole" ADD VALUE 'TEAM';

-- DropForeignKey
ALTER TABLE "contract_parties" DROP CONSTRAINT "contract_parties_stakeholderId_fkey";

-- DropForeignKey
ALTER TABLE "expenses" DROP CONSTRAINT "expenses_stakeholderId_fkey";

-- DropForeignKey
ALTER TABLE "invoices" DROP CONSTRAINT "invoices_quotationId_fkey";

-- DropForeignKey
ALTER TABLE "projects" DROP CONSTRAINT "projects_quotationId_fkey";

-- DropForeignKey
ALTER TABLE "quotation_line_items" DROP CONSTRAINT "quotation_line_items_quotationId_fkey";

-- DropForeignKey
ALTER TABLE "quotation_line_items" DROP CONSTRAINT "quotation_line_items_rateCardId_fkey";

-- DropForeignKey
ALTER TABLE "quotations" DROP CONSTRAINT "quotations_clientId_fkey";

-- DropForeignKey
ALTER TABLE "quotations" DROP CONSTRAINT "quotations_createdById_fkey";

-- DropIndex
DROP INDEX "clients_email_key";

-- DropIndex
DROP INDEX "invoices_invoiceNumber_key";

-- DropIndex
DROP INDEX "invoices_quotationId_key";

-- DropIndex
DROP INDEX "projects_quotationId_key";

-- DropIndex
DROP INDEX "users_email_key";

-- AlterTable
ALTER TABLE "channels" ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "clients" ADD COLUMN     "currency" TEXT,
ADD COLUMN     "importance" "ClientImportance" NOT NULL DEFAULT 'NORMAL',
ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "contract_parties" DROP COLUMN "stakeholderId";

-- AlterTable
ALTER TABLE "contracts" ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "expenses" DROP COLUMN "stakeholderId",
ADD COLUMN     "clientId" TEXT,
ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "files" ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "folders" ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "invoice_line_items" ADD COLUMN     "billableItemId" TEXT,
ADD COLUMN     "contentItemId" TEXT,
ADD COLUMN     "isFree" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "kind" "LineItemKind" NOT NULL DEFAULT 'CUSTOM';

-- AlterTable
ALTER TABLE "invoices" DROP COLUMN "quotationId",
ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "project_members" ADD COLUMN     "addedById" TEXT;

-- AlterTable
ALTER TABLE "projects" DROP COLUMN "quotationId",
ADD COLUMN     "cycleAmount" DECIMAL(12,2),
ADD COLUMN     "cycleEndDate" TIMESTAMP(3),
ADD COLUMN     "cycleStartDate" TIMESTAMP(3),
ADD COLUMN     "cycleUnit" "CycleUnit" NOT NULL DEFAULT 'MONTH',
ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "task_templates" ADD COLUMN     "organizationId" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "tasks" ADD COLUMN     "approvedAt" TIMESTAMP(3),
ADD COLUMN     "approverId" TEXT,
ADD COLUMN     "assignmentStatus" "AssignmentStatus" NOT NULL DEFAULT 'NONE',
ADD COLUMN     "clientId" TEXT,
ADD COLUMN     "content" TEXT,
ADD COLUMN     "contentItemId" TEXT,
ADD COLUMN     "cycleId" TEXT,
ADD COLUMN     "extraNote" TEXT,
ADD COLUMN     "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "kind" "TaskKind" NOT NULL DEFAULT 'GENERAL',
ADD COLUMN     "organizationId" TEXT NOT NULL,
ADD COLUMN     "preferredAssigneeId" TEXT,
ADD COLUMN     "referenceFileId" TEXT,
ADD COLUMN     "referenceUrl" TEXT,
ADD COLUMN     "revision" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "submittedAt" TIMESTAMP(3),
ADD COLUMN     "topic" TEXT,
ALTER COLUMN "projectId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "designation" "Designation",
ADD COLUMN     "designationId" TEXT,
ADD COLUMN     "organizationId" TEXT NOT NULL,
ADD COLUMN     "passwordHash" TEXT,
ADD COLUMN     "passwordSetAt" TIMESTAMP(3),
ALTER COLUMN "role" SET DEFAULT 'TEAM';

-- DropTable
DROP TABLE "company_settings";

-- DropTable
DROP TABLE "quotation_line_items";

-- DropTable
DROP TABLE "quotations";

-- DropTable
DROP TABLE "rate_cards";

-- DropTable
DROP TABLE "stakeholders";

-- DropEnum
DROP TYPE "QuotationStatus";

-- DropEnum
DROP TYPE "StakeholderRole";

-- DropEnum
DROP TYPE "StakeholderType";

-- CreateTable
CREATE TABLE "trial_requests" (
    "id" TEXT NOT NULL,
    "agencyName" TEXT NOT NULL,
    "contactName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "location" TEXT,
    "website" TEXT,
    "teamSize" TEXT,
    "services" TEXT,
    "message" TEXT,
    "status" "TrialRequestStatus" NOT NULL DEFAULT 'NEW',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "trial_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "designations" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "canBeAssignedWork" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "designations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_deliverables" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "creativeTypeId" TEXT NOT NULL,
    "qtyPerCycle" INTEGER NOT NULL,
    "notes" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "project_deliverables_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_cycles" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "status" "CycleStatus" NOT NULL DEFAULT 'OPEN',
    "closedAt" TIMESTAMP(3),
    "closedById" TEXT,
    "invoiceId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "project_cycles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "billable_items" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "projectId" TEXT,
    "cycleId" TEXT,
    "contentItemId" TEXT,
    "taskId" TEXT,
    "label" TEXT NOT NULL,
    "kind" "BillableKind" NOT NULL,
    "flaggedById" TEXT,
    "amount" DECIMAL(12,2),
    "status" "BillableStatus" NOT NULL DEFAULT 'PENDING_PRICING',
    "invoiceId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "billable_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "creative_types" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "icon" TEXT,
    "color" TEXT,
    "countsAsShoot" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "creative_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "content_items" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "projectId" TEXT,
    "date" TIMESTAMP(3) NOT NULL,
    "creativeTypeId" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "description" TEXT,
    "referenceUrl" TEXT,
    "referenceFileId" TEXT,
    "status" "ContentStatus" NOT NULL DEFAULT 'PLANNED',
    "isExtra" BOOLEAN NOT NULL DEFAULT false,
    "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
    "carriedFromId" TEXT,
    "countAgainstPrevMonth" BOOLEAN NOT NULL DEFAULT false,
    "cycleId" TEXT,
    "billingIntent" "BillingIntent" NOT NULL DEFAULT 'INCLUDED',
    "carryMode" "CarryMode",
    "submittedAt" TIMESTAMP(3),
    "approvedAt" TIMESTAMP(3),
    "postedAt" TIMESTAMP(3),
    "teamApprovedAt" TIMESTAMP(3),
    "clientApprovedAt" TIMESTAMP(3),
    "invoicedInId" TEXT,
    "reviewToken" TEXT,
    "reviewTokenExpiresAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "content_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_deliveries" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "method" "DeliveryMethod" NOT NULL,
    "fileId" TEXT,
    "url" TEXT,
    "note" TEXT,
    "deliveredById" TEXT,
    "deliveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_reviews" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "decision" "ReviewDecision" NOT NULL,
    "comments" TEXT,
    "reviewedById" TEXT,
    "reviewedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "change_requests" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "requestedById" TEXT,
    "note" TEXT NOT NULL,
    "status" "ChangeRequestStatus" NOT NULL DEFAULT 'OPEN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),

    CONSTRAINT "change_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "receipts" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "invoiceId" TEXT,
    "amount" DECIMAL(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "method" "ReceiptMethod" NOT NULL DEFAULT 'BANK_TRANSFER',
    "reference" TEXT,
    "receiptNumber" TEXT,
    "notes" TEXT,
    "attachmentUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "receipts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organizations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'My Agency',
    "slug" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "website" TEXT,
    "address" TEXT,
    "city" TEXT,
    "country" TEXT,
    "logoUrl" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "dateFormat" TEXT NOT NULL DEFAULT 'MMM D, YYYY',
    "taxRegistrations" JSONB,
    "letterheadLogoUrl" TEXT,
    "letterheadHeader" TEXT,
    "letterheadFooter" TEXT,
    "letterheadAddress" TEXT,
    "letterheadPhone" TEXT,
    "letterheadEmail" TEXT,
    "letterheadWebsite" TEXT,
    "letterheadColor" TEXT NOT NULL DEFAULT '#6366f1',
    "letterheadTemplate" TEXT NOT NULL DEFAULT 'CLASSIC',
    "letterheadConfig" TEXT,
    "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false,
    "onboardedAt" TIMESTAMP(3),
    "plan" "PlanTier" NOT NULL DEFAULT 'TRIAL',
    "trialEndsAt" TIMESTAMP(3),
    "uploadLimitMb" INTEGER NOT NULL DEFAULT 200,
    "requireAssignmentApproval" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "review_batches" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "revokedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "review_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "follow_ups" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "assignedToId" TEXT NOT NULL,
    "note" TEXT NOT NULL,
    "dueAt" TIMESTAMP(3) NOT NULL,
    "status" "FollowUpStatus" NOT NULL DEFAULT 'PENDING',
    "snoozedTo" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "follow_ups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_runs" (
    "id" TEXT NOT NULL,
    "jobName" TEXT NOT NULL,
    "runDate" TEXT NOT NULL,
    "ranAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_packages" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "startMonth" TIMESTAMP(3) NOT NULL,
    "endMonth" TIMESTAMP(3),
    "billingAmount" DECIMAL(12,2),
    "currency" TEXT,
    "notes" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "client_packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "package_quotas" (
    "id" TEXT NOT NULL,
    "packageId" TEXT NOT NULL,
    "creativeTypeId" TEXT NOT NULL,
    "monthlyQty" INTEGER NOT NULL,

    CONSTRAINT "package_quotas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendar_events" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3),
    "kind" "EventKind" NOT NULL DEFAULT 'OTHER',
    "clientId" TEXT,
    "reminderDaysBefore" INTEGER,
    "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "calendar_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_lists" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_lists_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "personal_items" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdById" TEXT,
    "listId" TEXT,
    "title" TEXT NOT NULL,
    "note" TEXT,
    "date" TIMESTAMP(3) NOT NULL,
    "time" TEXT,
    "starred" BOOLEAN NOT NULL DEFAULT false,
    "done" BOOLEAN NOT NULL DEFAULT false,
    "doneAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "personal_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "status_history" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT NOT NULL,
    "changedById" TEXT,
    "changedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,

    CONSTRAINT "status_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "link" TEXT,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "trial_requests_status_idx" ON "trial_requests"("status");

-- CreateIndex
CREATE INDEX "designations_organizationId_idx" ON "designations"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "designations_organizationId_slug_key" ON "designations"("organizationId", "slug");

-- CreateIndex
CREATE INDEX "project_deliverables_projectId_idx" ON "project_deliverables"("projectId");

-- CreateIndex
CREATE UNIQUE INDEX "project_deliverables_projectId_creativeTypeId_key" ON "project_deliverables"("projectId", "creativeTypeId");

-- CreateIndex
CREATE INDEX "project_cycles_projectId_status_idx" ON "project_cycles"("projectId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "project_cycles_projectId_startDate_key" ON "project_cycles"("projectId", "startDate");

-- CreateIndex
CREATE INDEX "billable_items_organizationId_status_idx" ON "billable_items"("organizationId", "status");

-- CreateIndex
CREATE INDEX "billable_items_clientId_status_idx" ON "billable_items"("clientId", "status");

-- CreateIndex
CREATE INDEX "billable_items_cycleId_idx" ON "billable_items"("cycleId");

-- CreateIndex
CREATE INDEX "creative_types_organizationId_isActive_idx" ON "creative_types"("organizationId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "creative_types_organizationId_slug_key" ON "creative_types"("organizationId", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "content_items_reviewToken_key" ON "content_items"("reviewToken");

-- CreateIndex
CREATE INDEX "content_items_cycleId_status_idx" ON "content_items"("cycleId", "status");

-- CreateIndex
CREATE INDEX "content_items_organizationId_clientId_date_idx" ON "content_items"("organizationId", "clientId", "date");

-- CreateIndex
CREATE INDEX "content_items_clientId_status_idx" ON "content_items"("clientId", "status");

-- CreateIndex
CREATE INDEX "content_items_organizationId_date_idx" ON "content_items"("organizationId", "date");

-- CreateIndex
CREATE INDEX "task_deliveries_taskId_revision_idx" ON "task_deliveries"("taskId", "revision");

-- CreateIndex
CREATE INDEX "task_reviews_taskId_revision_idx" ON "task_reviews"("taskId", "revision");

-- CreateIndex
CREATE INDEX "change_requests_taskId_status_idx" ON "change_requests"("taskId", "status");

-- CreateIndex
CREATE INDEX "receipts_clientId_idx" ON "receipts"("clientId");

-- CreateIndex
CREATE INDEX "receipts_invoiceId_idx" ON "receipts"("invoiceId");

-- CreateIndex
CREATE INDEX "receipts_receivedAt_idx" ON "receipts"("receivedAt");

-- CreateIndex
CREATE INDEX "receipts_organizationId_idx" ON "receipts"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "review_batches_token_key" ON "review_batches"("token");

-- CreateIndex
CREATE INDEX "review_batches_clientId_idx" ON "review_batches"("clientId");

-- CreateIndex
CREATE INDEX "follow_ups_organizationId_status_dueAt_idx" ON "follow_ups"("organizationId", "status", "dueAt");

-- CreateIndex
CREATE INDEX "follow_ups_clientId_idx" ON "follow_ups"("clientId");

-- CreateIndex
CREATE UNIQUE INDEX "job_runs_jobName_runDate_key" ON "job_runs"("jobName", "runDate");

-- CreateIndex
CREATE INDEX "client_packages_clientId_isActive_idx" ON "client_packages"("clientId", "isActive");

-- CreateIndex
CREATE INDEX "client_packages_organizationId_idx" ON "client_packages"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "package_quotas_packageId_creativeTypeId_key" ON "package_quotas"("packageId", "creativeTypeId");

-- CreateIndex
CREATE INDEX "calendar_events_organizationId_date_idx" ON "calendar_events"("organizationId", "date");

-- CreateIndex
CREATE INDEX "task_lists_userId_sortOrder_idx" ON "task_lists"("userId", "sortOrder");

-- CreateIndex
CREATE INDEX "personal_items_userId_date_idx" ON "personal_items"("userId", "date");

-- CreateIndex
CREATE INDEX "personal_items_userId_listId_idx" ON "personal_items"("userId", "listId");

-- CreateIndex
CREATE INDEX "status_history_entityType_entityId_idx" ON "status_history"("entityType", "entityId");

-- CreateIndex
CREATE INDEX "status_history_organizationId_idx" ON "status_history"("organizationId");

-- CreateIndex
CREATE INDEX "notifications_userId_readAt_idx" ON "notifications"("userId", "readAt");

-- CreateIndex
CREATE INDEX "notifications_userId_createdAt_idx" ON "notifications"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "channels_organizationId_idx" ON "channels"("organizationId");

-- CreateIndex
CREATE INDEX "clients_organizationId_idx" ON "clients"("organizationId");

-- CreateIndex
CREATE INDEX "contracts_organizationId_idx" ON "contracts"("organizationId");

-- CreateIndex
CREATE INDEX "expenses_clientId_idx" ON "expenses"("clientId");

-- CreateIndex
CREATE INDEX "expenses_projectId_idx" ON "expenses"("projectId");

-- CreateIndex
CREATE INDEX "expenses_organizationId_idx" ON "expenses"("organizationId");

-- CreateIndex
CREATE INDEX "files_projectId_idx" ON "files"("projectId");

-- CreateIndex
CREATE INDEX "files_clientId_idx" ON "files"("clientId");

-- CreateIndex
CREATE INDEX "files_folderId_idx" ON "files"("folderId");

-- CreateIndex
CREATE INDEX "files_status_idx" ON "files"("status");

-- CreateIndex
CREATE INDEX "files_organizationId_idx" ON "files"("organizationId");

-- CreateIndex
CREATE INDEX "folders_organizationId_idx" ON "folders"("organizationId");

-- CreateIndex
CREATE INDEX "invoices_status_clientId_idx" ON "invoices"("status", "clientId");

-- CreateIndex
CREATE INDEX "invoices_dueDate_idx" ON "invoices"("dueDate");

-- CreateIndex
CREATE INDEX "invoices_organizationId_idx" ON "invoices"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "invoices_organizationId_invoiceNumber_key" ON "invoices"("organizationId", "invoiceNumber");

-- CreateIndex
CREATE INDEX "projects_status_clientId_idx" ON "projects"("status", "clientId");

-- CreateIndex
CREATE INDEX "projects_clientId_idx" ON "projects"("clientId");

-- CreateIndex
CREATE INDEX "projects_organizationId_idx" ON "projects"("organizationId");

-- CreateIndex
CREATE INDEX "task_templates_organizationId_idx" ON "task_templates"("organizationId");

-- CreateIndex
CREATE INDEX "tasks_status_projectId_idx" ON "tasks"("status", "projectId");

-- CreateIndex
CREATE INDEX "tasks_projectId_deletedAt_idx" ON "tasks"("projectId", "deletedAt");

-- CreateIndex
CREATE INDEX "tasks_dueDate_idx" ON "tasks"("dueDate");

-- CreateIndex
CREATE INDEX "tasks_organizationId_idx" ON "tasks"("organizationId");

-- CreateIndex
CREATE INDEX "tasks_clientId_idx" ON "tasks"("clientId");

-- CreateIndex
CREATE INDEX "tasks_contentItemId_idx" ON "tasks"("contentItemId");

-- CreateIndex
CREATE INDEX "tasks_organizationId_assignmentStatus_idx" ON "tasks"("organizationId", "assignmentStatus");

-- CreateIndex
CREATE INDEX "users_organizationId_idx" ON "users"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "users_organizationId_email_key" ON "users"("organizationId", "email");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_designationId_fkey" FOREIGN KEY ("designationId") REFERENCES "designations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "designations" ADD CONSTRAINT "designations_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_addedById_fkey" FOREIGN KEY ("addedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_deliverables" ADD CONSTRAINT "project_deliverables_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_deliverables" ADD CONSTRAINT "project_deliverables_creativeTypeId_fkey" FOREIGN KEY ("creativeTypeId") REFERENCES "creative_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_cycles" ADD CONSTRAINT "project_cycles_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_cycles" ADD CONSTRAINT "project_cycles_closedById_fkey" FOREIGN KEY ("closedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "project_cycles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_contentItemId_fkey" FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_flaggedById_fkey" FOREIGN KEY ("flaggedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "billable_items" ADD CONSTRAINT "billable_items_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_contentItemId_fkey" FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_referenceFileId_fkey" FOREIGN KEY ("referenceFileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_approverId_fkey" FOREIGN KEY ("approverId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "project_cycles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_preferredAssigneeId_fkey" FOREIGN KEY ("preferredAssigneeId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "creative_types" ADD CONSTRAINT "creative_types_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_creativeTypeId_fkey" FOREIGN KEY ("creativeTypeId") REFERENCES "creative_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "project_cycles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_referenceFileId_fkey" FOREIGN KEY ("referenceFileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_carriedFromId_fkey" FOREIGN KEY ("carriedFromId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "content_items" ADD CONSTRAINT "content_items_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_deliveredById_fkey" FOREIGN KEY ("deliveredById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_reviews" ADD CONSTRAINT "task_reviews_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_reviews" ADD CONSTRAINT "task_reviews_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "change_requests" ADD CONSTRAINT "change_requests_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "change_requests" ADD CONSTRAINT "change_requests_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_templates" ADD CONSTRAINT "task_templates_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_contentItemId_fkey" FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "folders" ADD CONSTRAINT "folders_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "files" ADD CONSTRAINT "files_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "channels" ADD CONSTRAINT "channels_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_packages" ADD CONSTRAINT "client_packages_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_packages" ADD CONSTRAINT "client_packages_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_quotas" ADD CONSTRAINT "package_quotas_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "client_packages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_quotas" ADD CONSTRAINT "package_quotas_creativeTypeId_fkey" FOREIGN KEY ("creativeTypeId") REFERENCES "creative_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_lists" ADD CONSTRAINT "task_lists_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_listId_fkey" FOREIGN KEY ("listId") REFERENCES "task_lists"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "status_history" ADD CONSTRAINT "status_history_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "status_history" ADD CONSTRAINT "status_history_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


