-- PART 2 of 2: DATA
-- Generated by scripts/prepare-production-migration.ts
--
-- Backfills from prisma/manual-migrations, in dependency order. Every file
-- is idempotent, so re-running this is safe.
--
-- Run AFTER part 1 has committed:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f docs/PRODUCTION_MIGRATION_2_DATA.sql
--
-- Seed files excluded (they insert demo agencies): seed-v2-demo.sql, seed-vibrnd2-demo.sql
--
SET client_encoding = 'UTF8';

-- ------------------------------------------------------------------
-- 2026-07-passwords-and-trial-requests.sql
-- 2 statement(s) skipped: retired table(s)
-- ------------------------------------------------------------------

-- ============================================================
-- Manual migration for the production (Supabase) database.
-- Safe to run more than once — every statement is idempotent.
--
-- Apply it either with:
--   export DATABASE_URL="<supabase session-pooler URL, port 5432>"
--   npx prisma db push
-- OR paste this whole file into the Supabase SQL Editor and run it.
--
-- This brings production in line with the schema after adding password
-- login, the free-trial request form, and per-organization document
-- numbering. Without it, User creates/reads fail with Prisma P2022
-- ("column does not exist").
-- ============================================================

-- 1. Password login columns on users -------------------------
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "passwordHash"  TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "passwordSetAt" TIMESTAMP(3);

-- 2. Free-trial requests -------------------------------------
DO $$ BEGIN
  CREATE TYPE "TrialRequestStatus" AS ENUM ('NEW', 'CONTACTED', 'CONVERTED', 'DECLINED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "trial_requests" (
  "id"          TEXT NOT NULL,
  "agencyName"  TEXT NOT NULL,
  "contactName" TEXT NOT NULL,
  "email"       TEXT NOT NULL,
  "phone"       TEXT,
  "location"    TEXT,
  "website"     TEXT,
  "teamSize"    TEXT,
  "services"    TEXT,
  "message"     TEXT,
  "status"      "TrialRequestStatus" NOT NULL DEFAULT 'NEW',
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "trial_requests_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "trial_requests_status_idx" ON "trial_requests" ("status");
-- [skipped: targets a table v3 retires]
-- 
-- -- 3. Per-organization document numbering ---------------------
-- -- Drop the old GLOBAL unique on quotation.number / invoice.invoiceNumber
-- -- and replace with a per-organization composite unique.
-- ALTER TABLE "quotations" DROP CONSTRAINT IF EXISTS "quotations_number_key";
DROP INDEX IF EXISTS "quotations_number_key";
-- [skipped: targets a table v3 retires]
-- CREATE UNIQUE INDEX IF NOT EXISTS "quotations_organizationId_number_key"
--   ON "quotations" ("organizationId", "number");

ALTER TABLE "invoices" DROP CONSTRAINT IF EXISTS "invoices_invoiceNumber_key";
DROP INDEX IF EXISTS "invoices_invoiceNumber_key";
CREATE UNIQUE INDEX IF NOT EXISTS "invoices_organizationId_invoiceNumber_key"
  ON "invoices" ("organizationId", "invoiceNumber");

-- 4. Per-organization plan / trial / storage limit -----------
DO $$ BEGIN
  CREATE TYPE "PlanTier" AS ENUM ('TRIAL', 'FULL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "plan" "PlanTier" NOT NULL DEFAULT 'TRIAL';
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "trialEndsAt" TIMESTAMP(3);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "uploadLimitMb" INTEGER NOT NULL DEFAULT 200;

-- ------------------------------------------------------------------
-- 2026-08-phase1-foundations.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 1 (v2 foundations) — manual migration for production.
-- Safe to run more than once: every statement is idempotent.
--
-- Adds: Client.currency / Client.importance, User.designation,
--       status_history (universal audit), notifications (in-app).
-- Apply with:  export DATABASE_URL=... && npx prisma db push
-- OR paste this file into the Supabase SQL Editor and run it.
-- ============================================================

-- 1. Enums ---------------------------------------------------
DO $$ BEGIN
  CREATE TYPE "ClientImportance" AS ENUM ('NORMAL', 'IMPORTANT', 'VIP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "Designation" AS ENUM
    ('SMM', 'DESIGNER', 'EDITOR', 'HEAD_OF_DESIGN', 'PHOTOGRAPHER', 'SME', 'POC', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. New columns ---------------------------------------------
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "importance" "ClientImportance" NOT NULL DEFAULT 'NORMAL';
ALTER TABLE "users"   ADD COLUMN IF NOT EXISTS "designation" "Designation";

-- 3. Status history ------------------------------------------
CREATE TABLE IF NOT EXISTS "status_history" (
  "id"             TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "entityType"     TEXT NOT NULL,
  "entityId"       TEXT NOT NULL,
  "fromStatus"     TEXT,
  "toStatus"       TEXT NOT NULL,
  "changedById"    TEXT,
  "changedAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "note"           TEXT,
  CONSTRAINT "status_history_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "status_history_entityType_entityId_idx" ON "status_history" ("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "status_history_organizationId_idx" ON "status_history" ("organizationId");

DO $$ BEGIN
  ALTER TABLE "status_history"
    ADD CONSTRAINT "status_history_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "status_history"
    ADD CONSTRAINT "status_history_changedById_fkey"
    FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 4. Notifications -------------------------------------------
CREATE TABLE IF NOT EXISTS "notifications" (
  "id"             TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId"         TEXT NOT NULL,
  "type"           TEXT NOT NULL,
  "title"          TEXT NOT NULL,
  "body"           TEXT,
  "link"           TEXT,
  "readAt"         TIMESTAMP(3),
  "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "notifications_userId_readAt_idx" ON "notifications" ("userId", "readAt");
CREATE INDEX IF NOT EXISTS "notifications_userId_createdAt_idx" ON "notifications" ("userId", "createdAt");

DO $$ BEGIN
  ALTER TABLE "notifications"
    ADD CONSTRAINT "notifications_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "notifications"
    ADD CONSTRAINT "notifications_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase2-task-system.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 2 (Task System 2.0) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "AssignmentStatus" AS ENUM ('NONE','PENDING_HEAD_APPROVAL','APPROVED','REASSIGNED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE "DeliveryMethod" AS ENUM ('FILE_UPLOAD','LINK','WHATSAPP','SLACK','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE "ChangeRequestStatus" AS ENUM ('OPEN','RESOLVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Task: loosen projectId + new columns
ALTER TABLE "tasks" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "topic" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "referenceUrl" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "referenceFileId" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "extraNote" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "clientId" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "contentItemId" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "preferredAssigneeId" TEXT;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "assignmentStatus" "AssignmentStatus" NOT NULL DEFAULT 'NONE';
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "isAdHoc" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "tasks_clientId_idx" ON "tasks" ("clientId");
CREATE INDEX IF NOT EXISTS "tasks_contentItemId_idx" ON "tasks" ("contentItemId");
CREATE INDEX IF NOT EXISTS "tasks_organizationId_assignmentStatus_idx" ON "tasks" ("organizationId","assignmentStatus");

DO $$ BEGIN
  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_referenceFileId_fkey"
    FOREIGN KEY ("referenceFileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_preferredAssigneeId_fkey"
    FOREIGN KEY ("preferredAssigneeId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Delivery proof
CREATE TABLE IF NOT EXISTS "task_deliveries" (
  "id" TEXT NOT NULL,
  "taskId" TEXT NOT NULL,
  "method" "DeliveryMethod" NOT NULL,
  "fileId" TEXT,
  "url" TEXT,
  "note" TEXT,
  "deliveredById" TEXT,
  "deliveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "task_deliveries_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "task_deliveries_taskId_idx" ON "task_deliveries" ("taskId");
DO $$ BEGIN
  ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_taskId_fkey"
    FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_fileId_fkey"
    FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_deliveries" ADD CONSTRAINT "task_deliveries_deliveredById_fkey"
    FOREIGN KEY ("deliveredById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Change requests
CREATE TABLE IF NOT EXISTS "change_requests" (
  "id" TEXT NOT NULL,
  "taskId" TEXT NOT NULL,
  "requestedById" TEXT,
  "note" TEXT NOT NULL,
  "status" "ChangeRequestStatus" NOT NULL DEFAULT 'OPEN',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolvedAt" TIMESTAMP(3),
  CONSTRAINT "change_requests_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "change_requests_taskId_status_idx" ON "change_requests" ("taskId","status");
DO $$ BEGIN
  ALTER TABLE "change_requests" ADD CONSTRAINT "change_requests_taskId_fkey"
    FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "change_requests" ADD CONSTRAINT "change_requests_requestedById_fkey"
    FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase3-content-calendar.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 3 (Client Content Calendar) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "ContentStatus" AS ENUM
    ('PLANNED','ASSIGNED','IN_PROGRESS','IN_REVIEW','TEAM_APPROVED','CLIENT_APPROVED','SCHEDULED','POSTED','MISSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "creative_types" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "icon" TEXT,
  "color" TEXT,
  "countsAsShoot" BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "creative_types_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "creative_types_organizationId_slug_key" ON "creative_types" ("organizationId","slug");
CREATE INDEX IF NOT EXISTS "creative_types_organizationId_isActive_idx" ON "creative_types" ("organizationId","isActive");
DO $$ BEGIN
  ALTER TABLE "creative_types" ADD CONSTRAINT "creative_types_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "content_items" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "clientId" TEXT NOT NULL,
  "projectId" TEXT,
  "date" TIMESTAMP(3) NOT NULL,
  "creativeTypeId" TEXT NOT NULL,
  "topic" TEXT NOT NULL,
  "description" TEXT,
  "referenceUrl" TEXT,
  "referenceFileId" TEXT,
  "status" "ContentStatus" NOT NULL DEFAULT 'PLANNED',
  "isExtra" BOOLEAN NOT NULL DEFAULT false,
  "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
  "carriedFromId" TEXT,
  "countAgainstPrevMonth" BOOLEAN NOT NULL DEFAULT false,
  "postedAt" TIMESTAMP(3),
  "teamApprovedAt" TIMESTAMP(3),
  "clientApprovedAt" TIMESTAMP(3),
  "invoicedInId" TEXT,
  "reviewToken" TEXT,
  "reviewTokenExpiresAt" TIMESTAMP(3),
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "content_items_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "content_items_reviewToken_key" ON "content_items" ("reviewToken");
CREATE INDEX IF NOT EXISTS "content_items_organizationId_clientId_date_idx" ON "content_items" ("organizationId","clientId","date");
CREATE INDEX IF NOT EXISTS "content_items_clientId_status_idx" ON "content_items" ("clientId","status");
CREATE INDEX IF NOT EXISTS "content_items_organizationId_date_idx" ON "content_items" ("organizationId","date");
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_projectId_fkey"
    FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_creativeTypeId_fkey"
    FOREIGN KEY ("creativeTypeId") REFERENCES "creative_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_referenceFileId_fkey"
    FOREIGN KEY ("referenceFileId") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_carriedFromId_fkey"
    FOREIGN KEY ("carriedFromId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "content_items" ADD CONSTRAINT "content_items_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Task.contentItemId becomes a real FK
DO $$ BEGIN
  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_contentItemId_fkey"
    FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase4-my-calendar.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 4 (My Calendar) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS "personal_items" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "createdById" TEXT,
  "title" TEXT NOT NULL,
  "note" TEXT,
  "date" TIMESTAMP(3) NOT NULL,
  "time" TEXT,
  "done" BOOLEAN NOT NULL DEFAULT false,
  "doneAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "personal_items_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "personal_items_userId_date_idx" ON "personal_items" ("userId","date");
DO $$ BEGIN
  ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase5-events.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 5 (Master Calendar + events) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "EventKind" AS ENUM ('FESTIVAL','CAMPAIGN','SHOOT','INTERNAL','OTHER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "calendar_events" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "date" TIMESTAMP(3) NOT NULL,
  "endDate" TIMESTAMP(3),
  "kind" "EventKind" NOT NULL DEFAULT 'OTHER',
  "clientId" TEXT,
  "reminderDaysBefore" INTEGER,
  "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
  "notes" TEXT,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "calendar_events_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "calendar_events_organizationId_date_idx" ON "calendar_events" ("organizationId","date");
DO $$ BEGIN
  ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "calendar_events" ADD CONSTRAINT "calendar_events_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase6-packages.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 6 (Packages & quotas) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS "client_packages" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "clientId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "startMonth" TIMESTAMP(3) NOT NULL,
  "endMonth" TIMESTAMP(3),
  "billingAmount" DECIMAL(12,2),
  "currency" TEXT,
  "notes" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "client_packages_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "client_packages_clientId_isActive_idx" ON "client_packages" ("clientId","isActive");
CREATE INDEX IF NOT EXISTS "client_packages_organizationId_idx" ON "client_packages" ("organizationId");
DO $$ BEGIN
  ALTER TABLE "client_packages" ADD CONSTRAINT "client_packages_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "client_packages" ADD CONSTRAINT "client_packages_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "package_quotas" (
  "id" TEXT NOT NULL,
  "packageId" TEXT NOT NULL,
  "creativeTypeId" TEXT NOT NULL,
  "monthlyQty" INTEGER NOT NULL,
  CONSTRAINT "package_quotas_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "package_quotas_packageId_creativeTypeId_key" ON "package_quotas" ("packageId","creativeTypeId");
DO $$ BEGIN
  ALTER TABLE "package_quotas" ADD CONSTRAINT "package_quotas_packageId_fkey"
    FOREIGN KEY ("packageId") REFERENCES "client_packages"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "package_quotas" ADD CONSTRAINT "package_quotas_creativeTypeId_fkey"
    FOREIGN KEY ("creativeTypeId") REFERENCES "creative_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase7-invoicing.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 7 (Invoicing from packages) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "LineItemKind" AS ENUM ('PACKAGE','EXTRA','CUSTOM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "invoice_line_items" ADD COLUMN IF NOT EXISTS "kind" "LineItemKind" NOT NULL DEFAULT 'CUSTOM';
ALTER TABLE "invoice_line_items" ADD COLUMN IF NOT EXISTS "isFree" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "invoice_line_items" ADD COLUMN IF NOT EXISTS "contentItemId" TEXT;

DO $$ BEGIN
  ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_contentItemId_fkey"
    FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase8-notifications.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 8 (Notifications engine) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "FollowUpStatus" AS ENUM ('PENDING','DONE','SNOOZED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "follow_ups" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "clientId" TEXT NOT NULL,
  "assignedToId" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "dueAt" TIMESTAMP(3) NOT NULL,
  "status" "FollowUpStatus" NOT NULL DEFAULT 'PENDING',
  "snoozedTo" TIMESTAMP(3),
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "follow_ups_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "follow_ups_organizationId_status_dueAt_idx" ON "follow_ups" ("organizationId","status","dueAt");
CREATE INDEX IF NOT EXISTS "follow_ups_clientId_idx" ON "follow_ups" ("clientId");
DO $$ BEGIN
  ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_assignedToId_fkey"
    FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "job_runs" (
  "id" TEXT NOT NULL,
  "jobName" TEXT NOT NULL,
  "runDate" TEXT NOT NULL,
  "ranAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "job_runs_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "job_runs_jobName_runDate_key" ON "job_runs" ("jobName","runDate");

-- ------------------------------------------------------------------
-- 2026-08-phase9-bookings.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 9 (Photographer bookings) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "BookingStatus" AS ENUM ('REQUESTED','CONFIRMED','COMPLETED','CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "bookings" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "photographerId" TEXT NOT NULL,
  "clientId" TEXT,
  "projectId" TEXT,
  "contentItemId" TEXT,
  "startAt" TIMESTAMP(3) NOT NULL,
  "endAt" TIMESTAMP(3) NOT NULL,
  "location" TEXT,
  "notes" TEXT,
  "status" "BookingStatus" NOT NULL DEFAULT 'REQUESTED',
  "isAdHoc" BOOLEAN NOT NULL DEFAULT false,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "bookings_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "bookings_organizationId_startAt_idx" ON "bookings" ("organizationId","startAt");
CREATE INDEX IF NOT EXISTS "bookings_photographerId_startAt_idx" ON "bookings" ("photographerId","startAt");
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_photographerId_fkey"
    FOREIGN KEY ("photographerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_projectId_fkey"
    FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_contentItemId_fkey"
    FOREIGN KEY ("contentItemId") REFERENCES "content_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "bookings" ADD CONSTRAINT "bookings_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-phase10-review-links.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Phase 10 (Client review links) — manual migration for production.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- (ContentItem.reviewToken / reviewTokenExpiresAt shipped in Phase 3.)
-- ============================================================

CREATE TABLE IF NOT EXISTS "review_batches" (
  "id" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "clientId" TEXT NOT NULL,
  "month" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "revokedAt" TIMESTAMP(3),
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "review_batches_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "review_batches_token_key" ON "review_batches" ("token");
CREATE INDEX IF NOT EXISTS "review_batches_clientId_idx" ON "review_batches" ("clientId");
DO $$ BEGIN
  ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_clientId_fkey"
    FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "review_batches" ADD CONSTRAINT "review_batches_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-task-board-lists.sql
-- ------------------------------------------------------------------

-- ============================================================
-- Task board lists (Google-Tasks-style /tasks page) — production mirror.
-- Idempotent; apply with prisma db push OR paste into SQL editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS "task_lists" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "task_lists_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "task_lists_userId_sortOrder_idx" ON "task_lists" ("userId","sortOrder");
DO $$ BEGIN
  ALTER TABLE "task_lists" ADD CONSTRAINT "task_lists_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "personal_items" ADD COLUMN IF NOT EXISTS "listId" TEXT;
ALTER TABLE "personal_items" ADD COLUMN IF NOT EXISTS "starred" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS "personal_items_userId_listId_idx" ON "personal_items" ("userId","listId");
DO $$ BEGIN
  ALTER TABLE "personal_items" ADD CONSTRAINT "personal_items_listId_fkey"
    FOREIGN KEY ("listId") REFERENCES "task_lists"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------
-- 2026-08-v3-phase0-retire-modules.sql
-- 5 statement(s) skipped: retired table(s)
-- ------------------------------------------------------------------


-- [skipped: targets a table v3 retires]-- V3 Phase 0 — retire Quotations, Rate Cards, Stakeholders and Bookings.
-- --
-- -- The checked-in prisma/migrations history can't be replayed (see
-- -- docs/V3_CONTEXT.md "Naming corrections"), so schema changes are applied with
-- -- `prisma db push` and mirrored here as an idempotent script that can be run
-- -- against any environment. Safe to re-run.
-- --
-- -- Rows were exported to backups/retired-modules-<date>.json first
-- -- (scripts/export-retired-modules.ts).
-- 
-- BEGIN;
-- 
-- -- ─────────────────────────────────────────────────────────────
-- -- 1. Contract parties keep their meaning WITHOUT the Stakeholder
-- --    model: copy the stakeholder's name/email onto the party row
-- --    itself before the link disappears. Runs before any drop.
-- -- ─────────────────────────────────────────────────────────────
-- DO $$
-- BEGIN
--   IF EXISTS (SELECT 1 FROM information_schema.columns
--              WHERE table_name = 'contract_parties' AND column_name = 'stakeholderId')
--      AND EXISTS (SELECT 1 FROM information_schema.tables
--                  WHERE table_name = 'stakeholders') THEN
--     UPDATE contract_parties cp
--        SET name  = COALESCE(NULLIF(cp.name, ''), s.name),
--            email = COALESCE(cp.email, s.email)
--       FROM stakeholders s
--      WHERE cp."stakeholderId" = s.id;
--   END IF;
-- END $$;

-- ─────────────────────────────────────────────────────────────
-- 2. Drop the foreign-key columns that point at retired models.
--    Existing invoices, expenses and contracts keep every other
--    field, so they still open and render.
-- ─────────────────────────────────────────────────────────────
ALTER TABLE projects         DROP COLUMN IF EXISTS "quotationId";
ALTER TABLE invoices         DROP COLUMN IF EXISTS "quotationId";
ALTER TABLE expenses         DROP COLUMN IF EXISTS "stakeholderId";
ALTER TABLE contract_parties DROP COLUMN IF EXISTS "stakeholderId";
-- [skipped: targets a table v3 retires]
-- 
-- -- ─────────────────────────────────────────────────────────────
-- -- 3. Drop the tables. Order matters: children before parents.
-- -- ─────────────────────────────────────────────────────────────
-- DROP TABLE IF EXISTS quotation_line_items;
-- [skipped: targets a table v3 retires]
-- DROP TABLE IF EXISTS quotations;
-- [skipped: targets a table v3 retires]
-- DROP TABLE IF EXISTS rate_cards;
DROP TABLE IF EXISTS bookings;
-- [skipped: targets a table v3 retires]
-- DROP TABLE IF EXISTS stakeholders;

-- ─────────────────────────────────────────────────────────────
-- 4. Drop the enums that no surviving column uses.
--    ContractPartyType keeps its STAKEHOLDER value — an external
--    party is now just a name/email on the contract_parties row.
-- ─────────────────────────────────────────────────────────────
DROP TYPE IF EXISTS "QuotationStatus";
DROP TYPE IF EXISTS "StakeholderType";
DROP TYPE IF EXISTS "StakeholderRole";
DROP TYPE IF EXISTS "BookingStatus";

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-phase1-roles-designations.sql
-- ------------------------------------------------------------------

-- V3 Phase 1 — four-role model + dynamic designations.
--
-- The structural half (UserRole gains SMM/TEAM, the designations table,
-- users.designationId, organizations.requireAssignmentApproval) is applied by
-- `prisma db push`. This file is the DATA half: it moves existing users onto
-- the new tiers and gives every organization a starting set of job labels.
-- Idempotent — safe to re-run.

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- 1. v2's MEMBER tier becomes v3's TEAM. MEMBER stays in the enum
--    as a deprecated value so any row this misses still reads.
-- ─────────────────────────────────────────────────────────────
UPDATE users SET role = 'TEAM' WHERE role = 'MEMBER';

-- ─────────────────────────────────────────────────────────────
-- 2. Seed the default job labels for every organization.
--    SME and POC can't have work assigned to them — they're advisory
--    roles, so they're excluded from assignment pickers.
-- ─────────────────────────────────────────────────────────────
INSERT INTO designations ("id", "organizationId", "name", "slug", "isActive", "canBeAssignedWork", "sortOrder", "createdAt", "updatedAt")
SELECT
  'desg_' || o.id || '_' || d.slug,
  o.id, d.name, d.slug, TRUE, d.assignable, d.ord, NOW(), NOW()
FROM organizations o
CROSS JOIN (VALUES
  ('Editor',       'editor',       TRUE,  0),
  ('Photographer', 'photographer', TRUE,  1),
  ('Videographer', 'videographer', TRUE,  2),
  ('Copywriter',   'copywriter',   TRUE,  3),
  ('Designer',     'designer',     TRUE,  4),
  ('Head of Design','head-of-design', TRUE, 6),
  ('SME',          'sme',          FALSE, 7),
  ('POC',          'poc',          FALSE, 8)
) AS d(name, slug, assignable, ord)
ON CONFLICT ("organizationId", "slug") DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 3. Carry each user's old enum designation onto the new FK, so
--    nobody loses their job label in the move.
--
--    v2's enum had an SMM value, but v3 makes SMM a ROLE — planning
--    is an access tier, not a craft — so it has no designation to
--    map onto and is deliberately absent below.
-- ─────────────────────────────────────────────────────────────
UPDATE users u
   SET "designationId" = d.id
  FROM designations d
 WHERE d."organizationId" = u."organizationId"
   AND u."designationId" IS NULL
   AND u.designation IS NOT NULL
   AND d.slug = CASE u.designation::text
                  WHEN 'DESIGNER'       THEN 'designer'
                  WHEN 'EDITOR'         THEN 'editor'
                  WHEN 'HEAD_OF_DESIGN' THEN 'head-of-design'
                  WHEN 'PHOTOGRAPHER'   THEN 'photographer'
                  WHEN 'SME'            THEN 'sme'
                  WHEN 'POC'            THEN 'poc'
                  ELSE NULL
                END;

COMMIT;


-- ------------------------------------------------------------------
-- 2026-08-v3-phase2-project-commercial.sql
-- ------------------------------------------------------------------

-- V3 Phase 2 — the project becomes the commercial unit.
--
-- Structure (Project.cycleAmount/cycleUnit/cycleStartDate/cycleEndDate,
-- project_deliverables, project_cycles, project_members.addedById,
-- Task.kind, the ProjectRole/CycleUnit/CycleStatus/TaskKind enums) is
-- applied by `prisma db push`. This mirrors it for other environments and
-- carries the one piece of data movement that push can't do.
-- Idempotent — safe to re-run.

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- Projects created before v3 have startDate/endDate but no cycle
-- window, so they'd generate no cycles and their Plan tab would be
-- empty. Seed the cycle period from the dates they already have.
-- ─────────────────────────────────────────────────────────────
UPDATE projects
   SET "cycleStartDate" = "startDate"
 WHERE "cycleStartDate" IS NULL
   AND "startDate" IS NOT NULL;

UPDATE projects
   SET "cycleEndDate" = "endDate"
 WHERE "cycleEndDate" IS NULL
   AND "endDate" IS NOT NULL
   -- A retainer with an end date is unusual; leave open-ended ones alone.
   AND type = 'ONE_TIME';

COMMIT;

-- Cycles themselves are generated lazily by lib/cycles.ts (ensureCycles),
-- which runs whenever a project's cycles are read, so there's nothing to
-- backfill here. Client packages are converted to retainer projects by
-- scripts/migrate-packages-to-projects.ts, which is idempotent and must be
-- run once per environment:
--
--   npx tsx scripts/migrate-packages-to-projects.ts --dry-run
--   npx tsx scripts/migrate-packages-to-projects.ts


-- ------------------------------------------------------------------
-- 2026-08-v3-phase3-planning.sql
-- ------------------------------------------------------------------

-- V3 Phase 3 — the SMM planning surface.
--
-- Structure (ContentItem.cycleId/billingIntent/carryMode/submittedAt/
-- approvedAt, the BillingIntent and CarryMode enums, and the SUBMITTED /
-- APPROVED / CHANGES_REQUESTED / CARRIED_FORWARD content statuses) is
-- applied by `prisma db push`. This mirrors it and carries the backfill.
-- Idempotent — safe to re-run.

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- Items already flagged as extras under v2 carry that meaning
-- forward, so cycle close (Phase 6) sees them as billable rather
-- than silently folding them into the package.
-- ─────────────────────────────────────────────────────────────
UPDATE content_items
   SET "billingIntent" = 'EXTRA_BILLABLE'
 WHERE "isExtra" = TRUE
   AND "billingIntent" = 'INCLUDED';

-- ─────────────────────────────────────────────────────────────
-- Attach existing project-linked items to the cycle their date
-- falls in. Items planned against a client but no project keep a
-- null cycleId and still render — the client roll-up reads them
-- by date, not by cycle.
-- ─────────────────────────────────────────────────────────────
UPDATE content_items ci
   SET "cycleId" = pc.id
  FROM project_cycles pc
 WHERE ci."cycleId" IS NULL
   AND ci."projectId" = pc."projectId"
   AND ci.date >= pc."startDate"
   AND ci.date <= pc."endDate";

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-phase4-junior-workspace.sql
-- ------------------------------------------------------------------

-- V3 Phase 4 — the junior's workspace.
--
-- Structure (Task.kind/revision/approverId/submittedAt/approvedAt/cycleId and
-- the CHANGES_REQUESTED task status) is applied by `prisma db push`. This
-- mirrors it and carries the data movement.
-- Idempotent — safe to re-run.

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- 1. Custom task lists are retired: v3 has My List plus one
--    automatic list per project. Fold every personal item that
--    lived in a custom list back into My List so nothing is lost
--    (the list rows themselves stay for one release, unused).
-- ─────────────────────────────────────────────────────────────
UPDATE personal_items
   SET "listId" = NULL
 WHERE "listId" IS NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- 2. Tasks that already point at a content item are content work
--    by definition, so they read correctly in the new lists.
-- ─────────────────────────────────────────────────────────────
UPDATE tasks
   SET kind = 'CONTENT_WORK'
 WHERE kind = 'GENERAL'
   AND "contentItemId" IS NOT NULL
   AND "deletedAt" IS NULL;

-- ─────────────────────────────────────────────────────────────
-- 3. Attach existing project tasks to the cycle their due date
--    falls in, so Phase 6's cycle close sees them.
-- ─────────────────────────────────────────────────────────────
UPDATE tasks t
   SET "cycleId" = pc.id
  FROM project_cycles pc
 WHERE t."cycleId" IS NULL
   AND t."projectId" = pc."projectId"
   AND t."dueDate" IS NOT NULL
   AND t."dueDate" >= pc."startDate"
   AND t."dueDate" <= pc."endDate";

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-phase5-review-loop.sql
-- ------------------------------------------------------------------

-- V3 Phase 5 — submit → review → approve/changes → post.
--
-- Structure (TaskDelivery.revision, the task_reviews table, the
-- ReviewDecision enum) is applied by `prisma db push`. This mirrors it and
-- carries the fold-in of the older ChangeRequest rows.
-- Idempotent — safe to re-run.

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- v2's ChangeRequest could only say "please change this" — it had
-- no way to record an approval, which is why v3 replaces it with
-- TaskReview. Carry the existing rows across as round-1 change
-- requests so no feedback is lost. change_requests stays in place,
-- unused, for one release.
-- ─────────────────────────────────────────────────────────────
INSERT INTO task_reviews ("id", "taskId", "revision", "decision", "comments", "reviewedById", "reviewedAt")
SELECT
  'rev_' || cr.id,
  cr."taskId",
  1,
  'CHANGES_REQUESTED',
  cr.note,
  cr."requestedById",
  cr."createdAt"
FROM change_requests cr
WHERE NOT EXISTS (
  SELECT 1 FROM task_reviews tr WHERE tr.id = 'rev_' || cr.id
);

-- Every existing delivery was a first hand-in.
UPDATE task_deliveries SET revision = 1 WHERE revision IS NULL;

COMMIT;


-- ------------------------------------------------------------------
-- 2026-08-v3-phase6-cycle-close.sql
-- ------------------------------------------------------------------

-- V3 Phase 6 — cycle close: carry forward, extras, complimentary.
--
-- Structure (the billable_items table plus the BillableKind and
-- BillableStatus enums) is applied by `prisma db push`. This mirrors it.
-- Idempotent — safe to re-run.
--
-- There is no backfill: billable items are produced by CLOSING a cycle, and
-- no cycle has been closed before this phase existed. Cycles already marked
-- closed by hand (there should be none) would need their lines generated by
-- reopening and re-closing them through the wizard.

BEGIN;

-- Belt and braces: v2 marked over-delivery with isExtra only. Anything still
-- carrying that flag without a billing intent is a billable extra, so cycle
-- close offers it in step 3 rather than folding it silently into the package.
UPDATE content_items
   SET "billingIntent" = 'EXTRA_BILLABLE'
 WHERE "isExtra" = TRUE
   AND "billingIntent" = 'INCLUDED';

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-phase7-invoicing.sql
-- ------------------------------------------------------------------

-- V3 Phase 7 — invoicing from closed cycles.
--
-- Structure (InvoiceLineItem.billableItemId, and COMPLIMENTARY / ADHOC_TASK
-- added to LineItemKind) is applied by `prisma db push`. This mirrors it.
-- Idempotent — safe to re-run.
--
-- Existing invoices are untouched: their lines keep kind CUSTOM/PACKAGE/EXTRA
-- and a null billableItemId, which is exactly right — they predate the
-- billing bridge and were never built from one.

BEGIN;

-- v2 marked complimentary lines with isFree and a zero price. v3 gives them
-- their own kind so the PDF can section them under "Complimentary" and show
-- the token amount rather than a silent zero. Only touches lines that are
-- unmistakably complimentary: free, but not a deliberate zero-rated custom
-- line the user typed themselves.
UPDATE invoice_line_items
   SET kind = 'COMPLIMENTARY'
 WHERE "isFree" = TRUE
   AND kind = 'EXTRA';

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-fix-smm-designation.sql
-- ------------------------------------------------------------------

-- V3 correction — "SMM" was never a designation.
--
-- Phase 1 seeded a designation called SMM alongside a ROLE called SMM, so the
-- same word appeared in two adjacent columns meaning two different things.
-- An admin could read as "Admin / SMM" and nobody could say which was true.
--
-- The distinction v3 actually draws (docs/V3_CONTEXT.md §2):
--   Role        what you may DO      — OWNER, ADMIN, MANAGER, SMM, TEAM
--   Designation what you DO          — Editor, Photographer, Copywriter, …
--
-- Planning projects and reviewing work is an access tier, not a craft, so it
-- belongs to Role alone. Anyone who plans is role SMM; the label is redundant.
-- Idempotent — safe to re-run.

BEGIN;

-- Release anyone holding it. Their ROLE already says whether they plan.
UPDATE users u
   SET "designationId" = NULL
  FROM designations d
 WHERE u."designationId" = d.id
   AND d.slug = 'smm';

-- Then remove the label itself.
DELETE FROM designations WHERE slug = 'smm';

-- The same reasoning applies to "Head of Design": it IS a real job, so it
-- stays. Only SMM collided with a role name.

COMMIT;

-- ------------------------------------------------------------------
-- 2026-08-v3-drop-creative-type-emoji.sql
-- ------------------------------------------------------------------

-- Creative types are identified by colour, not emoji.
--
-- Phase 3 seeded an emoji into creative_types.icon for every default type
-- (Reel = clapperboard, Post = framed picture, and so on). Those rendered
-- across the calendar, the plan, the package tab and the review page.
--
-- Emoji draw differently on every OS, ignore the type's own colour, and read
-- as decoration in a tool people work in all day. Every creative type already
-- carries a colour, so the colour became the mark — see CreativeTypeDot.
--
-- The `icon` COLUMN stays: an agency that deliberately sets a lucide icon name
-- can still do so. Only the seeded emoji are cleared.
--
-- Idempotent — safe to re-run.

BEGIN;

UPDATE creative_types
   SET icon = NULL
 WHERE icon IS NOT NULL
   -- Anything outside plain ASCII is an emoji we seeded, never a lucide name.
   AND icon !~ '^[a-zA-Z0-9_-]+$';

COMMIT;

